#!/usr/bin/env bash
ln -sf cartelet/{*.ml{,i},libmincaml.S} .
ln -sf cartelet/lib .
cd shootout; ln -sf cartelet/Makefile .
cd ../bytemark; ln -sf cartelet/Makefile .
cd ../min-rt; ln -sf cartelet/globals.s .
cd ..
